import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useData } from '../context/DataContext';
import { useAutenticacao } from '../context/AutenticacaoContext';
import { api } from '../services/api';
import { Bar, Doughnut } from 'react-chartjs-2';
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, ArcElement, Tooltip, Legend } from 'chart.js';
import { ModalRelatorioPDF } from '../components/ModalRelatorioPDF';
import { ModalConfirmacao } from '../components/ModalConfirmacao';

ChartJS.register(CategoryScale, LinearScale, BarElement, ArcElement, Tooltip, Legend);
type Period = '7d' | '14d' | '30d' | 'all';
type Range = { start: string; end: string; title: string };
const COLORS = ['#4f8ef7','#7c5cfc','#3ecf8e','#f5c842','#f5874a','#f55a5a','#00bcd4','#e91e63'];
const dateKey = (d: Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const fromKey = (key: string) => new Date(`${key}T12:00:00`);
const logDate = (item: any) => item.data || String(item.estudadoEm || item.registradoEm || item.criadoEm || item.createdAt || '').slice(0, 10);
const formatTime = (sec: number) => { const h = Math.floor(sec/3600); const m = Math.floor(sec%3600/60); return h ? `${h}h${m ? String(m).padStart(2,'0') : ''}` : `${m}min`; };
const pctColor = (pct: number | null) => pct == null ? '#94a3b8' : pct >= 80 ? '#10b981' : pct >= 60 ? '#f59e0b' : '#ef4444';
const rangeDays = (start: string, end: string) => { const out: string[]=[]; const d=fromKey(start); const last=fromKey(end); while(d<=last){out.push(dateKey(d));d.setDate(d.getDate()+1);} return out; };

export const HistoricoPage: React.FC = () => {
  const { alunoId, activeContestId, activeContest, getArray } = useData();
  const { usuario } = useAutenticacao();
  const [period, setPeriod] = useState<Period>('all'); const [detail, setDetail] = useState<Range | null>(null); const [editLog, setEditLog] = useState<any | null>(null); const [shareMessage, setShareMessage] = useState('');
  const [modalPDF, setModalPDF] = useState(false);
  const [logParaDeletar, setLogParaDeletar] = useState<any | null>(null);
  const [allSessions,setAllSessions]=useState<any[]>([]);const[allQuestions,setAllQuestions]=useState<any[]>([]);const[sims,setSims]=useState<any[]>([]);const[cronograma,setCronograma]=useState<any>(null);const[carregando,setCarregando]=useState(true);const[erro,setErro]=useState('');
  const carregar=useCallback(async()=>{if(!activeContestId)return;setErro('');try{const[s,q,si,c]=await Promise.all([api.listarSessoes(alunoId,activeContestId),api.listarQuestoes(alunoId,activeContestId),api.listarSimulados(alunoId,activeContestId),api.obterCronograma(alunoId,activeContestId)]);setAllSessions(s.sessoes||[]);setAllQuestions(q.registros||[]);setSims(si.simulados||[]);setCronograma(c.cronograma?.concursoId===activeContestId?c.cronograma:null)}catch(e:any){setErro(e.message)}finally{setCarregando(false)}},[activeContestId,alunoId]);
  useEffect(()=>{carregar()},[carregar]);
  const currentYear = new Date().getFullYear(); const matters = getArray('materias').filter((x:any)=>x.concursoId===activeContestId); const topics = getArray('topicos').filter((t:any)=>matters.some((m:any)=>m.id===t.materiaId)); const subs = getArray('subtopicos').filter((s:any)=>topics.some((t:any)=>t.id===s.topicoId));
  const availableYears = useMemo(() => { const years = new Set<number>([currentYear]); [...allSessions,...allQuestions].forEach(x=>{const y=Number(logDate(x).slice(0,4));if(y)years.add(y);}); return [...years].sort((a,b)=>b-a); }, [allSessions, allQuestions, currentYear]);
  const [year, setYear] = useState(currentYear);
  const today = dateKey(new Date());
  const cutoff = useMemo(() => { if(period==='all') return ''; const d=new Date(); d.setDate(d.getDate()-(period==='7d'?6:period==='14d'?13:29)); return dateKey(d); },[period]);
  const sessions = allSessions.filter(x=>!cutoff||logDate(x)>=cutoff); const questions = allQuestions.filter(x=>!cutoff||logDate(x)>=cutoff);
  const totalSeconds = sessions.reduce((n:number,x:any)=>n+(Number(x.segundos)||0),0); const totalQ=questions.reduce((n:number,x:any)=>n+(Number(x.resolvidas)||0),0); const totalCorrect=questions.reduce((n:number,x:any)=>n+(Number(x.acertos)||0),0); const accuracy=totalQ?Math.round(totalCorrect/totalQ*100):null;
  const allSeconds=allSessions.reduce((n:number,x:any)=>n+(Number(x.segundos)||0),0); const allQ=allQuestions.reduce((n:number,x:any)=>n+(Number(x.resolvidas)||0),0);
  const simPcts=sims.map((s:any)=>Number(s.pct ?? (s.totalQuestoes?Math.round((s.questoesAcertos||0)/s.totalQuestoes*100):NaN))).filter(Number.isFinite); const simAvg=simPcts.length?Math.round(simPcts.reduce((a,b)=>a+b,0)/simPcts.length):null;
  const studiedDates=new Set(allSessions.map(logDate).filter(Boolean)); let streak=0; const streakCursor=new Date(); if(!studiedDates.has(dateKey(streakCursor)))streakCursor.setDate(streakCursor.getDate()-1); while(studiedDates.has(dateKey(streakCursor))){streak++;streakCursor.setDate(streakCursor.getDate()-1);}
  const matterStats = useMemo(()=>matters.map((m:any)=>{const ss=sessions.filter((x:any)=>x.materiaId===m.id);const qs=questions.filter((x:any)=>x.materiaId===m.id);const sec=ss.reduce((n:number,x:any)=>n+(Number(x.segundos)||0),0);const resolved=qs.reduce((n:number,x:any)=>n+(Number(x.resolvidas)||0),0);const correct=qs.reduce((n:number,x:any)=>n+(Number(x.acertos)||0),0);const mts=topics.filter((t:any)=>t.materiaId===m.id);const msubs=subs.filter((s:any)=>s.materiaId===m.id);const coverageItems=[...mts.filter((t:any)=>!msubs.some((s:any)=>s.topicoId===t.id)),...msubs];return {...m,sec,resolved,correct,pct:resolved?Math.round(correct/resolved*100):null,done:coverageItems.filter((x:any)=>x.estudado).length,count:coverageItems.length};}),[matters,questions,sessions,subs,topics]);
  const performance = matterStats.filter((m:any)=>m.resolved>=1&&m.pct!=null).sort((a:any,b:any)=>b.pct-a.pct); const easiest=performance.slice(0,3); const hardest=[...performance].sort((a:any,b:any)=>a.pct-b.pct).slice(0,3);
  const firstDate=[...allSessions,...allQuestions].map(logDate).filter(Boolean).sort()[0]||today; const chartStart=cutoff||firstDate; const rawChartDays=rangeDays(chartStart,today); const chartDays=rawChartDays.length>90?rawChartDays.filter((_,i)=>i%Math.ceil(rawChartDays.length/60)===0||i===rawChartDays.length-1):rawChartDays;
  const dailyData={labels:chartDays.map(k=>fromKey(k).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})),datasets:[{label:'Minutos',data:chartDays.map(k=>Math.round(sessions.filter(x=>logDate(x)===k).reduce((n:number,x:any)=>n+(Number(x.segundos)||0),0)/60)),backgroundColor:'rgba(79,142,247,.72)',yAxisID:'y'},{label:'Questões',data:chartDays.map(k=>questions.filter(x=>logDate(x)===k).reduce((n:number,x:any)=>n+(Number(x.resolvidas)||0),0)),backgroundColor:'rgba(62,207,142,.72)',yAxisID:'y1'}]};
  const matterChart={labels:performance.map((m:any)=>m.nome),datasets:[{label:'Acertos (%)',data:performance.map((m:any)=>m.pct),backgroundColor:performance.map((m:any)=>pctColor(m.pct)),borderRadius:6}]};
  const pieItems=matterStats.filter((m:any)=>m.sec>0); const pieData={labels:pieItems.map((m:any)=>m.nome),datasets:[{data:pieItems.map((m:any)=>Math.round(m.sec/60)),backgroundColor:COLORS,borderWidth:0}]};
  const todayMatter=matters.map((m:any)=>({name:m.nome,minutes:Math.round(allSessions.filter((x:any)=>x.materiaId===m.id&&logDate(x)===today).reduce((n:number,x:any)=>n+(Number(x.segundos)||0),0)/60),questions:allQuestions.filter((x:any)=>x.materiaId===m.id&&logDate(x)===today).reduce((n:number,x:any)=>n+(Number(x.resolvidas)||0),0)})).filter(x=>x.minutes||x.questions); const todayChart={labels:todayMatter.map(x=>x.name),datasets:[{label:'Minutos',data:todayMatter.map(x=>x.minutes),backgroundColor:'rgba(79,142,247,.75)'},{label:'Questões',data:todayMatter.map(x=>x.questions),backgroundColor:'rgba(245,200,66,.75)'}]};

  const heatDays=useMemo(()=>{const out:any[]=[];const d=new Date();d.setDate(d.getDate()-83);for(let i=0;i<84;i++){const key=dateKey(d);out.push({key,date:new Date(d),sec:allSessions.filter((x:any)=>logDate(x)===key).reduce((n:number,x:any)=>n+(Number(x.segundos)||0),0),q:allQuestions.filter((x:any)=>logDate(x)===key).reduce((n:number,x:any)=>n+(Number(x.resolvidas)||0),0)});d.setDate(d.getDate()+1);}return out;},[allQuestions,allSessions]); const maxHeat=Math.max(1,...heatDays.map(x=>x.sec));
  const months=useMemo(()=>Array.from({length:12},(_,month)=>{const start=`${year}-${String(month+1).padStart(2,'0')}-01`;const last=new Date(year,month+1,0);const end=dateKey(last);const ss=allSessions.filter((x:any)=>logDate(x)>=start&&logDate(x)<=end);const qs=allQuestions.filter((x:any)=>logDate(x)>=start&&logDate(x)<=end);return {month,name:new Date(year,month,1).toLocaleDateString('pt-BR',{month:'long'}),start,end,sec:ss.reduce((n:number,x:any)=>n+(Number(x.segundos)||0),0),q:qs.reduce((n:number,x:any)=>n+(Number(x.resolvidas)||0),0),days:new Set([...ss,...qs].map(logDate)).size};}),[allQuestions,allSessions,year]);
  const detailData=useMemo(()=>{if(!detail)return null;const ss=allSessions.filter((x:any)=>logDate(x)>=detail.start&&logDate(x)<=detail.end);const qs=allQuestions.filter((x:any)=>logDate(x)>=detail.start&&logDate(x)<=detail.end);const rows=matters.map((m:any)=>{const ms=ss.filter((x:any)=>x.materiaId===m.id);const mq=qs.filter((x:any)=>x.materiaId===m.id);const sec=ms.reduce((n:number,x:any)=>n+(Number(x.segundos)||0),0);const resolved=mq.reduce((n:number,x:any)=>n+(Number(x.resolvidas)||0),0);const correct=mq.reduce((n:number,x:any)=>n+(Number(x.acertos)||0),0);return {id:m.id,name:m.nome,sec,resolved,correct,pct:resolved?Math.round(correct/resolved*100):null};}).filter(x=>x.sec||x.resolved);const config=cronograma?.configuracao||{};const keys=['dom','seg','ter','qua','qui','sex','sab'];const expectedSec=rangeDays(detail.start,detail.end).reduce((n,k)=>n+(Number(config.horas?.[keys[fromKey(k).getDay()]])||0)*3600,0);const studiedSec=ss.reduce((n:number,x:any)=>n+(Number(x.segundos)||0),0);return {ss,qs,rows,studiedSec,expectedSec,balance:studiedSec-expectedSec};},[allQuestions,allSessions,cronograma,detail,matters]);
  const recent=[...allSessions.map((x:any)=>({...x,logType:'sessoes',label:'Sessão de estudo'})),...allQuestions.map((x:any)=>({...x,logType:'questoes',label:'Lançamento de questões'}))].sort((a:any,b:any)=>String(logDate(b)).localeCompare(String(logDate(a)))).slice(0,50);

  const saveEdit=async()=>{if(!editLog)return;setErro('');try{const data=`${editLog.data||logDate(editLog)}T12:00:00Z`;if(editLog.logType==='sessoes')await api.alterarSessao(alunoId,editLog.id,{segundos:Math.max(0,Number(editLog.minutes)||0)*60,observacoes:editLog.observacoes||'',estudadoEm:data});else{const resolved=Math.max(0,Number(editLog.resolvidas)||0),correct=Math.min(resolved,Math.max(0,Number(editLog.acertos)||0));await api.alterarQuestoes(alunoId,editLog.id,{resolvidas:resolved,acertos:correct,erros:resolved-correct,registradoEm:data})}setEditLog(null);await carregar()}catch(e:any){setErro(e.message)}};
  const deleteLog = (log: any) => {
    setLogParaDeletar(log);
  };

  const confirmarExclusaoLog = async () => {
    if (!logParaDeletar) return;
    setErro('');
    try {
      if (logParaDeletar.logType === 'sessoes') await api.desativarSessao(alunoId, logParaDeletar.id);
      else await api.desativarQuestoes(alunoId, logParaDeletar.id);
      setLogParaDeletar(null);
      await carregar();
    } catch (e: any) {
      setErro(e.message);
    }
  };

  const shareMetrics=async()=>{const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#0d0f14';ctx.fillRect(0,0,1080,1350);const gradient=ctx.createLinearGradient(0,0,1080,0);gradient.addColorStop(0,'#4f8ef7');gradient.addColorStop(1,'#7c5cfc');ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,16);ctx.fillStyle='#e8eaf2';ctx.font='700 54px Inter, Arial';ctx.fillText('Chega Junto Concurseiro',70,105);ctx.font='700 38px Inter, Arial';ctx.fillText(activeContest?.nome||'Minhas métricas',70,170);ctx.fillStyle='#a1a6c2';ctx.font='24px Inter, Arial';ctx.fillText(`Relatório • ${new Date().toLocaleDateString('pt-BR')}`,70,212);const cards=[['Tempo estudado',formatTime(totalSeconds)],['Questões',String(totalQ)],['Taxa de acerto',accuracy==null?'—':`${accuracy}%`],['Sequência',`${streak} dias`]];cards.forEach(([label,value],i)=>{const x=70+(i%2)*480,y=275+Math.floor(i/2)*170;ctx.fillStyle='#13161e';ctx.fillRect(x,y,440,130);ctx.fillStyle='#a1a6c2';ctx.font='20px Inter, Arial';ctx.fillText(label,x+28,y+36);ctx.fillStyle=i===2?'#3ecf8e':'#e8eaf2';ctx.font='700 42px Inter, Arial';ctx.fillText(value,x+28,y+91);});ctx.fillStyle='#e8eaf2';ctx.font='700 30px Inter, Arial';ctx.fillText('Distribuição por matéria',70,680);const top=[...matterStats].sort((a:any,b:any)=>b.sec-a.sec).slice(0,6);const max=Math.max(1,...top.map((m:any)=>m.sec));top.forEach((m:any,i)=>{const y=735+i*78;ctx.fillStyle='#a1a6c2';ctx.font='22px Inter, Arial';ctx.fillText(m.nome.slice(0,42),70,y);ctx.fillStyle='#252836';ctx.fillRect(70,y+18,820,20);ctx.fillStyle=COLORS[i%COLORS.length];ctx.fillRect(70,y+18,820*m.sec/max,20);ctx.fillStyle='#e8eaf2';ctx.font='700 20px Inter, Arial';ctx.fillText(formatTime(m.sec),915,y+36);});const blob:Blob|null=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)return;try{if(navigator.clipboard&&'write'in navigator.clipboard&&typeof ClipboardItem!=='undefined'){await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);setShareMessage('Imagem copiada.');}else throw new Error();}catch{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`metricas-${activeContest?.nome||'track-concursos'}.png`;a.click();URL.revokeObjectURL(url);setShareMessage('Imagem baixada.');}setTimeout(()=>setShareMessage(''),2500);};

  const openDay=(key:string)=>setDetail({start:key,end:key,title:fromKey(key).toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'})});
  const allCoverage=[...topics.filter((t:any)=>!subs.some((s:any)=>s.topicoId===t.id)),...subs];
  if(carregando)return <div className="loading-state">Carregando histórico e métricas…</div>;
  return <div>
    {erro&&<div className="form-error">{erro}</div>}
    <div className="page-heading"><div><h1>📊 Métricas</h1><p>{activeContest?.nome} · análise completa da preparação</p></div><div className="heading-actions"><div className="period-chips">{(['7d','14d','30d','all'] as Period[]).map(p=><button className={period===p?'active':''} key={p} onClick={()=>setPeriod(p)}>{p==='all'?'Desde o início':p.replace('d',' dias')}</button>)}</div><button className="btn-primary" style={{ padding: '6px 14px', fontSize: '13px' }} onClick={() => setModalPDF(true)}>📄 Gerar Relatório PDF</button><button className="btn-secondary" onClick={shareMetrics}>📷 Copiar imagem</button></div></div>
    {shareMessage&&<div className="success-banner">{shareMessage}</div>}
    <div className="stat-grid metrics-stats"><div className="stat-card"><span>Tempo no período</span><strong>{formatTime(totalSeconds)}</strong><small>{formatTime(allSeconds)} no total</small></div><div className="stat-card"><span>Questões no período</span><strong>{totalQ}</strong><small>{allQ} no total</small></div><div className="stat-card"><span>Taxa de acerto</span><strong style={{color:pctColor(accuracy)}}>{accuracy==null?'—':`${accuracy}%`}</strong><small>{totalCorrect} acertos</small></div><div className="stat-card"><span>Sequência atual</span><strong>{streak}d</strong><small>dias consecutivos</small></div><div className="stat-card"><span>Média simulados</span><strong>{simAvg==null?'—':`${simAvg}%`}</strong><small>{simPcts.length} realizados</small></div></div>
    <section className="card-base metric-chart-card"><div className="card-title-row"><div><h2>Atividade por dia</h2><p>Tempo e questões no período selecionado.</p></div></div><div className="metric-chart"><Bar data={dailyData} options={{maintainAspectRatio:false,responsive:true,plugins:{legend:{labels:{color:'#a1a6c2',boxWidth:10}}},scales:{x:{ticks:{color:'#7f86a8',maxTicksLimit:15},grid:{display:false}},y:{position:'left',ticks:{color:'#7f86a8'},grid:{color:'rgba(255,255,255,.05)'}},y1:{position:'right',ticks:{color:'#3ecf8e'},grid:{display:false}}}}}/></div></section>
    <div className="metrics-grid-2"><section className="card-base metric-chart-card"><div className="card-title-row"><div><h2>Desempenho por matéria</h2><p>Percentual de acertos.</p></div></div><div className="metric-chart">{performance.length > 0 ? <Bar data={matterChart} options={{maintainAspectRatio:false,indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{min:0,max:100,ticks:{color:'#7f86a8'},grid:{color:'rgba(128,128,128,.15)'}},y:{ticks:{color:'#7f86a8'},grid:{display:false}}}}}/> : <div style={{ height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)', fontSize: '0.9rem', gap: '8px' }}><span style={{ fontSize: '24px' }}>📝</span><span>Nenhuma questão resolvida neste período</span></div>}</div></section><section className="card-base metric-chart-card"><div className="card-title-row"><div><h2>Distribuição do tempo</h2><p>Participação de cada matéria.</p></div></div><div className="metric-chart"><Doughnut data={pieItems.length?pieData:{labels:['Sem estudo'],datasets:[{data:[1],backgroundColor:['#252836']}]}} options={{maintainAspectRatio:false,plugins:{legend:{position:'right',labels:{color:'#a1a6c2',boxWidth:10,font:{size:10}}}}}}/></div></section></div>
    <div className="rank-grid"><section className="card-base"><h2>✅ Maior facilidade</h2>{easiest.map((m:any,i)=><div key={m.id}><b>{i+1}</b><span>{m.nome}</span><strong style={{color:pctColor(m.pct)}}>{m.pct}%</strong><small>{m.resolved} questões</small></div>)}{!easiest.length&&<p>Resolva questões para gerar o ranking.</p>}</section><section className="card-base"><h2>⚠ Maior dificuldade</h2>{hardest.map((m:any,i)=><div key={m.id}><b>{i+1}</b><span>{m.nome}</span><strong style={{color:pctColor(m.pct)}}>{m.pct}%</strong><small>{m.resolved} questões</small></div>)}{!hardest.length&&<p>Resolva questões para gerar o ranking.</p>}</section></div>
    <section className="card-base today-metrics"><div className="card-title-row"><div><h2>Resumo de hoje</h2><p>Clique para abrir os detalhes completos.</p></div><button onClick={()=>openDay(today)}>Ver detalhes</button></div><div className="today-metric-summary"><div><strong>{formatTime(allSessions.filter((x:any)=>logDate(x)===today).reduce((n:number,x:any)=>n+(Number(x.segundos)||0),0))}</strong><span>estudados</span></div><div><strong>{allQuestions.filter((x:any)=>logDate(x)===today).reduce((n:number,x:any)=>n+(Number(x.resolvidas)||0),0)}</strong><span>questões</span></div><div className="today-chart"><Bar data={todayChart} options={{maintainAspectRatio:false,plugins:{legend:{labels:{color:'#a1a6c2',boxWidth:9}}},scales:{x:{ticks:{color:'#7f86a8'},grid:{display:false}},y:{ticks:{color:'#7f86a8'},grid:{color:'rgba(255,255,255,.05)'}}}}}/></div></div></section>
    <section className="card-base activity-section"><div className="card-title-row"><div><h2>Mapa de atividade</h2><p>Clique em um dia para ver sessões e questões.</p></div></div><div className="activity-heatmap">{heatDays.map(day=><button key={day.key} title={`${fromKey(day.key).toLocaleDateString('pt-BR')} · ${formatTime(day.sec)} · ${day.q} questões`} onClick={()=>openDay(day.key)} style={{background:day.sec?`color-mix(in srgb, var(--green) ${Math.max(18,day.sec/maxHeat*100)}%, var(--bg3))`:'var(--bg3)'}}><span>{day.date.getDate()}</span></button>)}</div></section>
    <section className="card-base annual-section"><div className="card-title-row"><div><h2>Retrospectiva anual</h2><p>Abra um mês ou o ano completo.</p></div><div className="annual-actions"><select className="form-control" value={year} onChange={e=>setYear(Number(e.target.value))}>{availableYears.map(y=><option key={y}>{y}</option>)}</select><button onClick={()=>setDetail({start:`${year}-01-01`,end:`${year}-12-31`,title:`Ano de ${year}`})}>Ver ano</button></div></div><div className="month-grid">{months.map(month=><button key={month.month} onClick={()=>setDetail({start:month.start,end:month.end,title:`${month.name} de ${year}`})}><strong>{month.name}</strong><span>{formatTime(month.sec)}</span><small>{month.q} questões · {month.days} dias ativos</small></button>)}</div></section>
    <div className="metrics-grid-2"><section className="card-base progress-panel"><h2>Progresso do edital</h2><div><span>Itens concluídos</span><strong>{allCoverage.filter((x:any)=>x.estudado).length}/{allCoverage.length}</strong></div><div className="mini-progress"><div style={{width:`${allCoverage.length?allCoverage.filter((x:any)=>x.estudado).length/allCoverage.length*100:0}%`}}/></div><div><span>Matérias iniciadas</span><strong>{matterStats.filter((m:any)=>m.sec>0).length}/{matters.length}</strong></div><div><span>Simulados realizados</span><strong>{simPcts.length}/{sims.length}</strong></div></section><section className="card-base matter-summary"><h2>Resumo por matéria</h2>{matterStats.map((m:any)=><div key={m.id}><span>{m.nome}</span><b>{formatTime(m.sec)}</b><b>{m.resolved}q</b><strong style={{color:pctColor(m.pct)}}>{m.pct==null?'—':`${m.pct}%`}</strong></div>)}</section></div>
    <section className="card-base log-panel"><div className="card-title-row"><div><h2>Lançamentos recentes</h2><p>Edite ou exclua sessões e questões.</p></div></div><div className="history-log-list">{recent.map((log:any)=>{const matter=matters.find((m:any)=>m.id===log.materiaId);const topic=topics.find((t:any)=>t.id===log.topicoId);return <div key={`${log.logType}-${log.id}`}><span>{log.logType==='sessoes'?'⏱':'📝'}</span><div><strong>{matter?.nome||log.label}</strong><small>{topic?.nome?`${topic.nome} · `:''}{logDate(log)?fromKey(logDate(log)).toLocaleDateString('pt-BR'):'Sem data'}</small></div><div className="history-log-values">{log.logType==='sessoes'?<b>{formatTime(Number(log.segundos)||0)}</b>:<><b>{log.resolvidas||0} questões</b><b>{log.resolvidas?Math.round((log.acertos||0)/log.resolvidas*100):0}%</b></>}</div><button className="icon-button" onClick={()=>setEditLog({...log,data:logDate(log),minutes:Math.round((log.segundos||0)/60)})}>✎</button><button className="icon-button danger" onClick={()=>deleteLog(log)}>×</button></div>})}</div></section>

    {detail&&detailData&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><section className="modal-card metrics-detail-modal" onClick={e=>e.stopPropagation()}><div className="modal-heading"><div><h2>{detail.title}</h2><p>{formatTime(detailData.studiedSec)} estudados · {detailData.qs.reduce((n:number,x:any)=>n+(Number(x.resolvidas)||0),0)} questões</p></div><button className="icon-button" onClick={()=>setDetail(null)}>×</button></div><div className="cycle-comparison"><div><span>Estudado</span><strong>{formatTime(detailData.studiedSec)}</strong></div><div><span>Meta do ciclo</span><strong>{formatTime(detailData.expectedSec)}</strong></div><div className={detailData.balance>=0?'positive':'negative'}><span>Saldo</span><strong>{detailData.balance>=0?'+':''}{formatTime(Math.abs(detailData.balance))}</strong></div></div><div className="detail-matter-list">{detailData.rows.map((row:any)=><div key={row.id}><span>{row.name}</span><b>{formatTime(row.sec)}</b><b>{row.resolved} questões</b><strong style={{color:pctColor(row.pct)}}>{row.pct==null?'—':`${row.pct}%`}</strong></div>)}{!detailData.rows.length&&<div className="compact-empty">Nenhuma atividade neste período.</div>}</div><div className="detail-log-columns"><div><h3>Sessões de estudo</h3>{detailData.ss.map((log:any)=><button key={log.id} onClick={()=>setEditLog({...log,logType:'sessoes',label:'Sessão de estudo',data:logDate(log),minutes:Math.round((log.segundos||0)/60)})}><span>{matters.find((m:any)=>m.id===log.materiaId)?.nome||'Estudo'}</span><b>{formatTime(log.segundos||0)}</b></button>)}</div><div><h3>Lançamentos de questões</h3>{detailData.qs.map((log:any)=><button key={log.id} onClick={()=>setEditLog({...log,logType:'questoes',label:'Lançamento de questões',data:logDate(log)})}><span>{matters.find((m:any)=>m.id===log.materiaId)?.nome||'Questões'}</span><b>{log.acertos||0}/{log.resolvidas||0}</b></button>)}</div></div></section></div>}
    {editLog&&<div className="modal-backdrop" onClick={()=>setEditLog(null)}><section className="modal-card small-modal" onClick={e=>e.stopPropagation()}><div className="modal-heading"><div><h2>Editar {editLog.label.toLowerCase()}</h2><p>Corrija os valores do lançamento.</p></div><button className="icon-button" onClick={()=>setEditLog(null)}>×</button></div><div className="form-fields"><label><span className="field-label">Data</span><input className="form-control" type="date" value={editLog.data || logDate(editLog) || ''} onChange={e=>setEditLog((p:any)=>({...p,data:e.target.value}))}/></label>{editLog.logType==='sessoes'?<><label><span className="field-label">Minutos</span><input className="form-control" type="number" min="0" value={editLog.minutes||''} onChange={e=>setEditLog((p:any)=>({...p,minutes:e.target.value}))}/></label><label style={{gridColumn:'1/-1'}}><span className="field-label">Observações</span><input className="form-control" value={editLog.observacoes||''} onChange={e=>setEditLog((p:any)=>({...p,observacoes:e.target.value}))}/></label></>:<><label><span className="field-label">Questões</span><input className="form-control" type="number" min="0" value={editLog.resolvidas||''} onChange={e=>setEditLog((p:any)=>({...p,resolvidas:e.target.value}))}/></label><label><span className="field-label">Acertos</span><input className="form-control" type="number" min="0" value={editLog.acertos||''} onChange={e=>setEditLog((p:any)=>({...p,acertos:e.target.value}))}/></label></>}</div><div className="modal-actions"><button className="btn-secondary" onClick={()=>setEditLog(null)}>Cancelar</button><button className="btn-primary" onClick={saveEdit}>Salvar alterações</button></div></section></div>}
    <ModalConfirmacao
      aberto={!!logParaDeletar}
      titulo="Confirmar exclusão"
      mensagem="Tem certeza que deseja apagar?"
      textoConfirmar="Sim, apagar"
      textoCancelar="Cancelar"
      aoConfirmar={confirmarExclusaoLog}
      aoCancelar={() => setLogParaDeletar(null)}
    />
    {modalPDF && (
      <ModalRelatorioPDF
        alunoNome={alunoId === 'eu' ? (usuario?.nome || 'Aluno') : 'Aluno'}
        concursoNome={activeContest?.nome || 'Concurso'}
        sessoes={allSessions}
        questoes={allQuestions}
        materias={matters}
        topicos={topics}
        subtopicos={subs}
        aoFechar={() => setModalPDF(false)}
      />
    )}
  </div>;
};
